; eugnet-patch.dll settings
[server]
ip = 127.0.0.1

eugnet-tcp = 21001
eugnet-tcp-alt = 21001

old-eugnet-tcp = 21001
old-eugnet-tcp-alt = 21001

war1-eugnet-tcp = 11000
war1-eugnet-tcp-alt = 11001

eugnet-http = 8080
eugnet-http-alt = 8080
eugnet-http-secure = 443

eugnet-stun = 3478

[settings]
; Values for Steel Division 2 only.
original-ip = 178.32.126.73
original-addr = tm.eugnet.com