public enum StatusCode : byte
{
    Success = 0x0,
    Refused = 0x1,
    ConnectionLost = 0x2,
    NotAvailable = 0x3,
    Timeout = 0x4,
    Full = 0x5,
    PendingClientListFull = 0x6,
    AlreadyInSession = 0x7,
    InvalidUserName = 0x8,
    InvalidSessionInfo = 0x9,
    IdReclaimed = 0xA,
    IncorrectIdentification = 0xB,
    IncorrectVersion = 0xC,
    DatabaseError = 0xD,
    UserDisconnectRequest = 0xF,
    Kicked = 0x10,
    AutoMatchNumPlayersChanged = 0x11,
    InvalidTicket = 0x12,
    NotAllowedToPlayThisGame = 0x13,
    Failed = 0x14,
    KickedAtEndGame = 0x15,
    KickedDueToBadPerformance = 0x16,
    BannedFromMultiplayer = 0x17,
    BannedFromDedicatedServer = 0x18,
    DedicatedServerRequiresPassword = 0x19,
    DedicatedServerInvalidPassword = 0x1A,
    BannedFromSession = 0x1B,
    VacCheckFailed = 0x1C,
    UnknownExternalApiAccount = 0x1D,
    NoDedicatedServerAvailable = 0x1E,
    CannotJoinWhilePlaying = 0x1F,
}